package(default_visibility = ["//visibility:public"])

cc_library(
    name = "error",
    hdrs = ["Error.h"],
    deps = [],
)

cc_library(
    name = "math",
    hdrs = ["Math.h"],
    deps = [],
)

cc_library(
    name = "utils",
    hdrs = ["Utils.h"],
    deps = [
      "//libs/expected-1.0:expected",
    ],
)