package(default_visibility = ["//visibility:public"])

cc_library(
    name = "expected",
    hdrs = glob([
      "include/**/*.h",
      "include/**/*.hpp",
    ]),
    strip_include_prefix = "include",
)
